export const cars = [
  "Audi",
  "A220-Mercedes",
  "aprilla",
  "Astar-Maruti",
  "Aston-Martin",
  "Baleno-Maruti",
  "Bolero-Mahindra",
  "B200-Mercedes",
  "C220D-Mercedes",
  "ciaz",
  "Camry-Toyota",
  "Corolla-Toyota",
  "Duster-Renault",
  "E220-Mercedes",
  "Ertiga-Maruti",
  "Estilo-Maruti",
  "Ferrari",
  "GWagon-Mercedes",
  "Gurkha",
  "Porsche Cayenne",
  "Rolls Royce Ghost",
  "Tata Tiago",
  "Harrier",
];
